### ISSUE TITLE
Failed to begin transaction - com.couchbase.cbforest.Database.beginTransaction

### ISSUE THREAD

**Issue by sethrosetter** [couchbaselabs/cbforest#71]
Found the following issue running (https://github.com/couchbaselabs/sync-gateway-tests/blob/master/tests/cbl-revisions.js) -https://gist.github.com/sethrosetter/b00106e612f6069d33cc07e335720059#file-gistfile1-txt-L66-L118

**Comment by snej** [comment]
```
ForestException{domain=2, code=-39}
at com.couchbase.cbforest.Database.beginTransaction(Native Method)
at com.couchbase.lite.store.ForestDBStore.beginTransaction(ForestDBStore.java:1235)
```
Error -39 means the ForestDB file handle was called reentrantly:
```c
    /**
     * DB handle is being used by another thread. Forestdb handles must not be
     * shared among multiple threads.
     */
    FDB_RESULT_HANDLE_BUSY = -39,
```
