### ISSUE TITLE
C4Error: variables of struct is not initialized with 0 on Android platform

### ISSUE THREAD

**Issue by hideki** [couchbaselabs/cbforest#78]
`C4Error error;` error is not initialized with 0. So C4error.domain is set random number.
In case of end of leaf, `selectNextLeaf()` returns `false` with C4Error.error = 0 without updating domain variable. 
```
04-07 19:18:40.723 3181-3194/? E/Database: Error in changesSince()
 ForestException{domain=-1642724708, code=0}
     at com.couchbase.cbforest.Document.selectNextLeaf(Native Method)
     at com.couchbase.cbforest.Document.selectNextLeaf(Document.java:47)
     at com.couchbase.lite.store.ForestBridge.getCurrentRevisionIDs(ForestBridge.java:86)
     at com.couchbase.lite.store.ForestDBStore.changesSince(ForestDBStore.java:731)
     at com.couchbase.lite.Database.getAllDocs(Database.java:1428)
     at com.couchbase.lite.Database.queryViewNamed(Database.java:2079)
     at com.couchbase.lite.Query.run(Query.java:433)
     at com.couchbase.lite.ApiTest.test12_AllDocumentsBySequence(ApiTest.java:399)
     at java.lang.reflect.Method.invokeNative(Native Method)
     at java.lang.reflect.Method.invoke(Method.java:515)
     at junit.framework.TestCase.runTest(TestCase.java:168)
     at junit.framework.TestCase.runBare(TestCase.java:134)
     at com.couchbase.lite.LiteTestCase.runBare(LiteTestCase.java:20)
     at com.couchbase.lite.LiteTestCaseWithDB.runBare(LiteTestCaseWithDB.java:95)
     at junit.framework.TestResult$1.protect(TestResult.java:115)
     at junit.framework.TestResult.runProtected(TestResult.java:133)
     at junit.framework.TestResult.run(TestResult.java:118)
     at junit.framework.TestCase.run(TestCase.java:124)
     at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
     at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
     at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
     at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1701)
```

**Comment by snej** [comment]
That commit isn't necessary. Clients of the C4 API do not have to initialize C4Error variables. The function you call will set the fields of the error if it fails.

The problem seems to be that there's a function that's failing without properly initializing the C4Error on the way out.

**Comment by snej** [comment]
> In case of end of leaf, selectNextLeaf() returns false with C4Error.error = 0

That indicates there's no error. The JNI wrapper shouldn't treat it as an exception — that's the fix that needs to be made.

**Comment by snej** [comment]
Change the JNI function like this:
```c++
    if (ok || error.code == 0 || error.domain == HTTPDomain)  // 404 or 410 don't trigger exceptions
```

**Comment by hideki** [comment]
@snej, thank you for your input. I will change it.
